app:
  port: ":8088"
  name: "go-wire-app"
database:
  driver: "mysql"
  address: "root:20011024@tcp(127.0.0.1:3306)/go_web_app_db?charset=utf8mb4&parseTime=True"
  maxIdleConns: 1
  maxOpenConns: 1
  connMaxLifetime: "1h"
  debugMode: true
  slowSQLThreshold: "0.5s"
  enableAutoMigrate: false
redis:
  addr: "localhost:6379"
  password: ""
  db: 0